### ISSUE TITLE
Resource not found for language ...

### ISSUE THREAD

**Issue by lterekhov** [makkarpov/scalingua#19]
I created in IDEA new empty project.

* plugins.sbt: `addSbtPlugin("ru.makkarpov" %% "scalingua-sbt" % "1.1.1")`
* dependency and plugin:
```
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "2.13.10"

lazy val root = (project in file("."))
  .enablePlugins(Scalingua)
  .settings(
    name := "scala-i18n",
    libraryDependencies += "ru.makkarpov" %% "scalingua" % "1.1.1"
  )
```
* implicits:
```
object SomeGlobal {
  implicit val messages = Messages.compiled()
  implicit val langId = LanguageId("ru-RU")
  implicit val language = Language.$providedLanguage
}
```
* Main:
```
import SomeGlobal._
import ru.makkarpov.scalingua.I18n._

object Main {
  def main(args: Array[String]): Unit = {
    val name = "leonid"
    println(t"Hello $name!")
  }
}
```

* po files:
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/42699761/207145253-bfcf9160-05bd-4f79-9f1d-198ba102f919.png">

i have next problem when run application:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Main$.main(Main.scala:7)
	at Main.main(Main.scala)
Caused by: java.lang.IllegalArgumentException: Resource not found for language ru_RU
	at locales.Language_ru_RU$.<clinit>(Language_ru_RU.scala:12)
	at locales.Languages$.<init>(Languages.scala:8)
	at locales.Languages$.<clinit>(Languages.scala:7)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at org.portablescala.reflect.LoadableModuleClass.loadModule(LoadableModuleClass.scala:17)
	at ru.makkarpov.scalingua.Messages$.compiled(Messages.scala:32)
	at SomeGlobal$.<clinit>(SomeGlobal.scala:4)
	... 2 more
```

would you suggest what i am doing wrong?

**Comment by makkarpov** [comment]
For generation to run, project must be compiled via SBT mechanics. Are you compiling via SBT or via some IDE-specific tool?

**Comment by makkarpov** [comment]
It appears that resources were not generated for locales for some reason.

Locale file consists of Scala class (which has been generated) and binary resource file which holds all strings.

Could you confirm that resource file does not appear after `sbt compile`?

**Comment by lterekhov** [comment]
yes, I confirm. no binary resources were created after `sbt compile`.

**Comment by makkarpov** [comment]
What does `show Compile / resourceGenerators` display? Scalingua uses [SBT standard mechanism](https://github.com/makkarpov/scalingua/blob/master/sbt-plugin/src/main/scala/ru/makkarpov/scalingua/plugin/Scalingua.scala#L88) to generate resources.

**Comment by lterekhov** [comment]
```
[IJ]show Compile / resourceGenerators
[info] * Task(_)
[info] * Task((taskDefinitionKey: ScopedKey(Scope(Select(ProjectRef(file:/Users/lterekhov/Projects/scala-i18n/,root)), Select(ConfigKey(compile)), Zero, Zero),packageLocales)))
```

It did not help. however, launching the application with the `sbt run` command result in the appearance of the necessary files. 

before that i used launcher mechanism IDEA

**Comment by makkarpov** [comment]
For IDEA, the checkbox 'Use SBT shell for builds & imports' must be checked in SBT settings to work

**Comment by lterekhov** [comment]
was expecting resource generation after the `sbt compile.` Is it possible to customize the generation after `sbt compile` or is this the correct behavior?

**Comment by makkarpov** [comment]
It could be that `compile` command does not have any dependency on resources, and SBT does not run resource generators. `packageBin` could work better, as it requires complete jar to be built.

**Comment by lterekhov** [comment]
thanks for the help! I'm closing the issue because I got the answers and the solution

**Comment by lterekhov** [comment]
little addition. `sbt copyResources` command works fine for me and generates binaries files
